# Generated by Django 4.1.5 on 2023-01-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=300)),
                ("price", models.FloatField(max_length=25)),
                ("picture", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField()),
            ],
        ),
    ]
